### ISSUE TITLE
registerPartials in heroku is stuck at /app/views/

### ISSUE THREAD

**Issue by juniormayhe** [pillarjs/hbs#145]
Every time I deploy an app to heroku, there is always an error firing about views path.

```
Error: Failed to lookup view "home.hbs" in views directory "/app/views"
    at EventEmitter.render (/app/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/app/node_modules/express/lib/response.js:971:7)
    at app.get (/app/my_app/server.js:52:14)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
```

I am trying to deploy an app with this structure

```
/my_root
   | - package.json
   my_app
         |  - server.js
         views
               | - home.hbs
               partials
                   | - footer.hbs
```
I tried to modify the server.js with different commands such as:

```
const express = require('express');
const hbs = require('hbs');

//get OS environment variable PORT for heroku or set 3000 if null
const port = process.env.PORT || 3000;
var app = express();

//tell express what is our view engine: handlebars
app.set('view engine', 'hbs');

//register partials folder
hbs.registerPartials('/app/my_app/views/partials'); //same error!
hbs.registerPartials(__dirname + '/views/partials');//same error!
hbs.registerPartials(__dirname + '/../views/partials');//same error!
hbs.registerPartials(__dirname + '/../../views/partials');//same error!

//render home template
app.get('/', (request, response)=>{
    response.render('home.hbs', {
        pageTitle: 'Home page',
        welcomeMessage: 'Welcome to some website',      
    });
})
```

no matter what I put, the error is always the same. 

I have two questions

1) Is this issue partial views folder issue related to `registerPartials `method? 
2) Is there a method to set the main views folder (since home.hbs is not found)?

**Comment by dougwilson** [comment]
Hi @juniormayhe that error is coming from Express.js itself, which is doing the initial lookup. You'll want to set the `"view"` Express.js setting:
```js
const express = require('express');
const hbs = require('hbs');

//get OS environment variable PORT for heroku or set 3000 if null
const port = process.env.PORT || 3000;
var app = express();

//tell express what is our view engine: handlebars
app.set('view engine', 'hbs');

//register views folder
app.set('views', __dirname + '/views');

//register partials folder
hbs.registerPartials(__dirname + '/views/partials');
```

I hope this helps!

**Comment by juniormayhe** [comment]
Thank you so much @dougwilson
It is working just fine, no more complains in `heroku logs`!

**Comment by dougwilson** [comment]
No problem, @juniormayhe !
